typography_spectrum: 0.6067024217918515
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.07404612749814987
  lightness: 0.022500849328935146
  saturation: 0.007015716750174761
  rhythmicContrast: 0.9864285835064948
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1350913611240685
analytics:
  google: null
  facebook: null
  twitter: null
name: JeremyPoland
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: I Found a Cat Today
description: Then I Ate It
purpose: []
